// <auto-generated />
using System;
using CuMusicClub.Domain.Enums;
using CuMusicClub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CuMusicClub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261006221200_RenameCoachToRoadie")]
    partial class RenameCoachToRoadie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "song_link_type", new[] { "youtube", "yandex_music", "soundcloud" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a partial Designer class. The full model snapshot is in ApplicationDbContextModelSnapshot.cs
            // This file is generated by EF Core migrations and should be regenerated by running:
            // dotnet ef migrations add RenameCoachToRoadie --project src/Infrastructure --startup-project src/Web

#pragma warning restore 612, 618
        }
    }
}
