// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	permissions "musicclubbot/backend/proto/permissions"
	user "musicclubbot/backend/proto/user"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TgLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw init data from Telegram Mini App (used for signature verification).
	InitData string `protobuf:"bytes,1,opt,name=init_data,json=initData,proto3" json:"init_data,omitempty"`
	// Optional explicit Telegram user id (if provided by the client).
	TgUserId      uint64 `protobuf:"varint,2,opt,name=tg_user_id,json=tgUserId,proto3" json:"tg_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TgLoginRequest) Reset() {
	*x = TgLoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TgLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgLoginRequest) ProtoMessage() {}

func (x *TgLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgLoginRequest.ProtoReflect.Descriptor instead.
func (*TgLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *TgLoginRequest) GetInitData() string {
	if x != nil {
		return x.InitData
	}
	return ""
}

func (x *TgLoginRequest) GetTgUserId() uint64 {
	if x != nil {
		return x.TgUserId
	}
	return 0
}

type AuthSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT access token.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Token issued-at and expiration (unix seconds).
	Iat uint64 `protobuf:"varint,2,opt,name=iat,proto3" json:"iat,omitempty"`
	Exp uint64 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	// Whether the user is already a member of the music club chat.
	IsChatMember bool `protobuf:"varint,4,opt,name=is_chat_member,json=isChatMember,proto3" json:"is_chat_member,omitempty"`
	// If not a member, link to request manual approval to join the chat.
	JoinRequestUrl string `protobuf:"bytes,5,opt,name=join_request_url,json=joinRequestUrl,proto3" json:"join_request_url,omitempty"`
	// Convenience: current user's profile data.
	Profile *user.User `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	// Permissions snapshot for the session.
	Permissions   *permissions.PermissionSet `protobuf:"bytes,7,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSession) Reset() {
	*x = AuthSession{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSession) ProtoMessage() {}

func (x *AuthSession) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSession.ProtoReflect.Descriptor instead.
func (*AuthSession) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthSession) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthSession) GetIat() uint64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *AuthSession) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *AuthSession) GetIsChatMember() bool {
	if x != nil {
		return x.IsChatMember
	}
	return false
}

func (x *AuthSession) GetJoinRequestUrl() string {
	if x != nil {
		return x.JoinRequestUrl
	}
	return ""
}

func (x *AuthSession) GetProfile() *user.User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *AuthSession) GetPermissions() *permissions.PermissionSet {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ProfileResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Profile       *user.User                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Permissions   *permissions.PermissionSet `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileResponse) GetProfile() *user.User {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ProfileResponse) GetPermissions() *permissions.PermissionSet {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x0emusicclub.auth\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11permissions.proto\x1a\n" +
	"user.proto\"K\n" +
	"\x0eTgLoginRequest\x12\x1b\n" +
	"\tinit_data\x18\x01 \x01(\tR\binitData\x12\x1c\n" +
	"\n" +
	"tg_user_id\x18\x02 \x01(\x04R\btgUserId\"\x9c\x02\n" +
	"\vAuthSession\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x10\n" +
	"\x03iat\x18\x02 \x01(\x04R\x03iat\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x04R\x03exp\x12$\n" +
	"\x0eis_chat_member\x18\x04 \x01(\bR\fisChatMember\x12(\n" +
	"\x10join_request_url\x18\x05 \x01(\tR\x0ejoinRequestUrl\x12.\n" +
	"\aprofile\x18\x06 \x01(\v2\x14.musicclub.user.UserR\aprofile\x12F\n" +
	"\vpermissions\x18\a \x01(\v2$.musicclub.permissions.PermissionSetR\vpermissions\"\x89\x01\n" +
	"\x0fProfileResponse\x12.\n" +
	"\aprofile\x18\x01 \x01(\v2\x14.musicclub.user.UserR\aprofile\x12F\n" +
	"\vpermissions\x18\x02 \x01(\v2$.musicclub.permissions.PermissionSetR\vpermissions2\xa6\x01\n" +
	"\vAuthService\x12P\n" +
	"\x11LoginWithTelegram\x12\x1e.musicclub.auth.TgLoginRequest\x1a\x1b.musicclub.auth.AuthSession\x12E\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x1f.musicclub.auth.ProfileResponseB(Z&musicclubbot/backend/proto/auth;authpbb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_proto_goTypes = []any{
	(*TgLoginRequest)(nil),            // 0: musicclub.auth.TgLoginRequest
	(*AuthSession)(nil),               // 1: musicclub.auth.AuthSession
	(*ProfileResponse)(nil),           // 2: musicclub.auth.ProfileResponse
	(*user.User)(nil),                 // 3: musicclub.user.User
	(*permissions.PermissionSet)(nil), // 4: musicclub.permissions.PermissionSet
	(*emptypb.Empty)(nil),             // 5: google.protobuf.Empty
}
var file_auth_proto_depIdxs = []int32{
	3, // 0: musicclub.auth.AuthSession.profile:type_name -> musicclub.user.User
	4, // 1: musicclub.auth.AuthSession.permissions:type_name -> musicclub.permissions.PermissionSet
	3, // 2: musicclub.auth.ProfileResponse.profile:type_name -> musicclub.user.User
	4, // 3: musicclub.auth.ProfileResponse.permissions:type_name -> musicclub.permissions.PermissionSet
	0, // 4: musicclub.auth.AuthService.LoginWithTelegram:input_type -> musicclub.auth.TgLoginRequest
	5, // 5: musicclub.auth.AuthService.GetProfile:input_type -> google.protobuf.Empty
	1, // 6: musicclub.auth.AuthService.LoginWithTelegram:output_type -> musicclub.auth.AuthSession
	2, // 7: musicclub.auth.AuthService.GetProfile:output_type -> musicclub.auth.ProfileResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
