{
 "title": "MusicClub Business Metrics",
 "tags": [
  "business",
  "musicclub"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "musicclub_users_total", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Songs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "musicclub_songs_total", "legendFormat": "Songs" }
   ]
  },
  {
   "title": "Song Roles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "musicclub_song_roles_total", "legendFormat": "Song Roles" }
   ]
  },
  {
   "title": "Role Assignments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "musicclub_song_role_assignments_total",
     "legendFormat": "Role Assignments"
    }
   ]
  },
  {
   "title": "Users in Roles",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "musicclub_song_role_assigned_users_total",
     "legendFormat": "Users in Roles"
    }
   ]
  },
  {
   "title": "Filled Songs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "musicclub_filled_songs_total", "legendFormat": "Filled Songs" }
   ]
  }
 ]
}