// @generated by protoc-gen-es v2.11.0 with parameter "target=js,import_extension=js"
// @generated from file auth.proto (package musicclub.auth, syntax proto3)
/* eslint-disable */

import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_permissions } from "./permissions_pb.js";
import { file_user } from "./user_pb.js";

/**
 * Describes the file auth.proto.
 */
export const file_auth =
  /*@__PURE__*/
  fileDesc(
    "CgphdXRoLnByb3RvEg5tdXNpY2NsdWIuYXV0aCIxCgtDcmVkZW50aWFscxIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSJuChNSZWdpc3RlclVzZXJSZXF1ZXN0EjAKC2NyZWRlbnRpYWxzGAEgASgLMhsubXVzaWNjbHViLmF1dGguQ3JlZGVudGlhbHMSJQoHcHJvZmlsZRgCIAEoCzIULm11c2ljY2x1Yi51c2VyLlVzZXIiJwoOUmVmcmVzaFJlcXVlc3QSFQoNcmVmcmVzaF90b2tlbhgBIAEoCSI4CglUb2tlblBhaXISFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkiKQoTVGdMb2dpbkxpbmtSZXNwb25zZRISCgpsb2dpbl9saW5rGAEgASgJIkgKDlRnTG9naW5SZXF1ZXN0EiIKBHVzZXIYASABKAsyFC5tdXNpY2NsdWIudXNlci5Vc2VyEhIKCnRnX3VzZXJfaWQYAiABKAQi5gEKC0F1dGhTZXNzaW9uEikKBnRva2VucxgBIAEoCzIZLm11c2ljY2x1Yi5hdXRoLlRva2VuUGFpchILCgNpYXQYAiABKAQSCwoDZXhwGAMgASgEEhYKDmlzX2NoYXRfbWVtYmVyGAQgASgIEhgKEGpvaW5fcmVxdWVzdF91cmwYBSABKAkSJQoHcHJvZmlsZRgGIAEoCzIULm11c2ljY2x1Yi51c2VyLlVzZXISOQoLcGVybWlzc2lvbnMYByABKAsyJC5tdXNpY2NsdWIucGVybWlzc2lvbnMuUGVybWlzc2lvblNldCJzCg9Qcm9maWxlUmVzcG9uc2USJQoHcHJvZmlsZRgBIAEoCzIULm11c2ljY2x1Yi51c2VyLlVzZXISOQoLcGVybWlzc2lvbnMYAiABKAsyJC5tdXNpY2NsdWIucGVybWlzc2lvbnMuUGVybWlzc2lvblNldCIuChlUZWxlZ3JhbVdlYkFwcEF1dGhSZXF1ZXN0EhEKCWluaXRfZGF0YRgBIAEoCTLWAwoLQXV0aFNlcnZpY2USTAoIUmVnaXN0ZXISIy5tdXNpY2NsdWIuYXV0aC5SZWdpc3RlclVzZXJSZXF1ZXN0GhsubXVzaWNjbHViLmF1dGguQXV0aFNlc3Npb24SQQoFTG9naW4SGy5tdXNpY2NsdWIuYXV0aC5DcmVkZW50aWFscxobLm11c2ljY2x1Yi5hdXRoLkF1dGhTZXNzaW9uEkQKB1JlZnJlc2gSHi5tdXNpY2NsdWIuYXV0aC5SZWZyZXNoUmVxdWVzdBoZLm11c2ljY2x1Yi5hdXRoLlRva2VuUGFpchJLCg5HZXRUZ0xvZ2luTGluaxIULm11c2ljY2x1Yi51c2VyLlVzZXIaIy5tdXNpY2NsdWIuYXV0aC5UZ0xvZ2luTGlua1Jlc3BvbnNlEkUKCkdldFByb2ZpbGUSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaHy5tdXNpY2NsdWIuYXV0aC5Qcm9maWxlUmVzcG9uc2USXAoSVGVsZWdyYW1XZWJBcHBBdXRoEikubXVzaWNjbHViLmF1dGguVGVsZWdyYW1XZWJBcHBBdXRoUmVxdWVzdBobLm11c2ljY2x1Yi5hdXRoLkF1dGhTZXNzaW9uQhxaGm11c2ljY2x1YmJvdC9iYWNrZW5kL3Byb3RvYgZwcm90bzM",
    [file_google_protobuf_empty, file_permissions, file_user],
  );

/**
 * Describes the message musicclub.auth.Credentials.
 * Use `create(CredentialsSchema)` to create a new message.
 */
export const CredentialsSchema = /*@__PURE__*/ messageDesc(file_auth, 0);

/**
 * Describes the message musicclub.auth.RegisterUserRequest.
 * Use `create(RegisterUserRequestSchema)` to create a new message.
 */
export const RegisterUserRequestSchema =
  /*@__PURE__*/
  messageDesc(file_auth, 1);

/**
 * Describes the message musicclub.auth.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema = /*@__PURE__*/ messageDesc(file_auth, 2);

/**
 * Describes the message musicclub.auth.TokenPair.
 * Use `create(TokenPairSchema)` to create a new message.
 */
export const TokenPairSchema = /*@__PURE__*/ messageDesc(file_auth, 3);

/**
 * Describes the message musicclub.auth.TgLoginLinkResponse.
 * Use `create(TgLoginLinkResponseSchema)` to create a new message.
 */
export const TgLoginLinkResponseSchema =
  /*@__PURE__*/
  messageDesc(file_auth, 4);

/**
 * Describes the message musicclub.auth.TgLoginRequest.
 * Use `create(TgLoginRequestSchema)` to create a new message.
 */
export const TgLoginRequestSchema = /*@__PURE__*/ messageDesc(file_auth, 5);

/**
 * Describes the message musicclub.auth.AuthSession.
 * Use `create(AuthSessionSchema)` to create a new message.
 */
export const AuthSessionSchema = /*@__PURE__*/ messageDesc(file_auth, 6);

/**
 * Describes the message musicclub.auth.ProfileResponse.
 * Use `create(ProfileResponseSchema)` to create a new message.
 */
export const ProfileResponseSchema = /*@__PURE__*/ messageDesc(file_auth, 7);

/**
 * Describes the message musicclub.auth.TelegramWebAppAuthRequest.
 * Use `create(TelegramWebAppAuthRequestSchema)` to create a new message.
 */
export const TelegramWebAppAuthRequestSchema =
  /*@__PURE__*/
  messageDesc(file_auth, 8);

/**
 * Authentication and membership gating for the app.
 *
 * @generated from service musicclub.auth.AuthService
 */
export const AuthService = /*@__PURE__*/ serviceDesc(file_auth, 0);
